context:
  version: 0.3.1

package:
  name: eva
  version: ${{ version }}

source:
  url: https://github.com/NerdyPepper/eva/archive/v${{ version }}.tar.gz
  sha256: d6a6eb8e0d46de1fea9bd00c361bd7955fcd7cc8f3310b786aad48c1dce7b3f7

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - eva --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Calculator REPL, similar to bc(1)
  homepage: https://github.com/NerdyPepper/eva
  repository: https://github.com/NerdyPepper/eva

extra:
  recipe-maintainers:
    - danielnachun
